import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { FXAAShader } from 'three/addons/shaders/FXAAShader.js';
import { makeWorld } from './world.js';
import { makeBaghdad } from './baghdad.js';
import { BaghdadMission } from './mission.js';
import { DIFFICULTIES } from './mission-rules.js';
import { makeCharacter } from './character.js';
import { C2System } from './c2.js';
import { GameAudio } from './audio.js';
import { damp,clamp,resolveCircle,integrateBullet,reloadAmmo,FIXED_STEP,MUZZLE_SPEED } from './physics.js';
const $=id=>document.getElementById(id),canvas=$('world');
document.body.classList.add('in-menu');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});}catch(error){$('play-label').textContent='WEBGL 2 NENÍ DOSTUPNÉ';$('load-error').classList.remove('hidden');$('load-error').textContent='Zapněte hardwarovou akceleraci a otevřete hru v aktuálním Chrome, Edge nebo Firefoxu.';throw error;}
renderer.info.autoReset=false;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.08,450),trainingScene=new THREE.Scene();
const trainingWorld=makeWorld(trainingScene);trainingWorld.id='training';trainingWorld.scene=trainingScene;trainingWorld.bounds={minX:-27.9,maxX:27.9,minZ:-62.8,maxZ:29};trainingWorld.spawn={x:0,z:18};
let world=trainingWorld,cityWorld,mission;scene.add(trainingScene);scene.background=trainingScene.background;scene.fog=trainingScene.fog;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new OutputPass());const fxaa=new ShaderPass(FXAAShader);composer.addPass(fxaa);
const grade=new ShaderPass({uniforms:{tDiffuse:{value:null},time:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D tDiffuse;uniform float time;varying vec2 vUv;void main(){vec3 c=texture2D(tDiffuse,vUv).rgb;float l=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(l),c,.86);c=mix(c*vec3(.91,1.0,.96),c,smoothstep(.1,.65,l));float v=1.-smoothstep(.28,.88,distance(vUv,vec2(.5,.45)))*.22;float n=fract(sin(dot(vUv+time,vec2(12.9898,78.233)))*43758.5453)-.5;gl_FragColor=vec4(c*v+n*.007,1.);}'});composer.addPass(grade);
const sound=new GameAudio(),state={position:new THREE.Vector3(0,0,18),yaw:0,pitch:-.12,crouched:false,aiming:false,sprint:false,speed:0,ammo:30,reserve:180,shots:0,hits:0,score:0,stamina:1,reload:0,recoil:0,time:0,mode:'menu',ready:false,level:'training',difficulty:'regular',health:100,kills:0,damageFlash:0,lastDamage:-100};
const c2=new C2System(world,state),keys=new Set(),velocity=new THREE.Vector3(),raycaster=new THREE.Raycaster(),cameraRay=new THREE.Raycaster(),bullets=[],tracers=[],decals=[],events=[];
let character,poseAccumulator=0,lastShot=-1,fireHeld=false,aimHeld=false,hasPlayed=false,notificationTimer=0,hitTimer=0,hitTextTimer=0,accumulator=0,lastTime=performance.now(),fpsTime=0,fpsFrames=0,frameTime=0,uiTime=0,stepTimer=0,reloadStage=0,sensitivity=1,dragLook=false,lastMouse=null;
const lookDirection=new THREE.Vector3(),aimPoint=new THREE.Vector3(),cameraTarget=new THREE.Vector3(),cameraDesired=new THREE.Vector3();
const sparks=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,0),new THREE.MeshBasicMaterial({color:'#e1bb82',transparent:true,opacity:.8}),180);sparks.instanceMatrix.setUsage(THREE.DynamicDrawUsage);sparks.frustumCulled=false;scene.add(sparks);const particles=[];
const casingsMesh=new THREE.InstancedMesh(new THREE.CylinderGeometry(.012,.013,.048,5),new THREE.MeshStandardMaterial({color:'#b3974a',metalness:.8,roughness:.43}),55);casingsMesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);casingsMesh.frustumCulled=false;scene.add(casingsMesh);const casings=[],dummy=new THREE.Object3D();sparks.count=0;casingsMesh.count=0;
function notify(text,seconds=3){$('notification').textContent=text;$('notification').style.opacity='1';notificationTimer=seconds;}
function currentForward(){return lookDirection.set(-Math.sin(state.yaw)*Math.cos(state.pitch),Math.sin(state.pitch),-Math.cos(state.yaw)*Math.cos(state.pitch));}
function exitPointer(){if(document.pointerLockElement)document.exitPointerLock();}
function releaseInput(){keys.clear();fireHeld=false;aimHeld=false;dragLook=false;state.aiming=false;state.sprint=false;}
async function play(){if(!state.ready||state.mode==='result')return;state.mode='playing';hasPlayed=true;$('menu').classList.add('hidden');document.body.classList.remove('in-menu');sound.start();try{if(canvas.requestPointerLock)await canvas.requestPointerLock();else throw new Error('Pointer lock unsupported');}catch{notify('Myš: pravé tlačítko držte pro otáčení a míření. Esc otevře nabídku.',5);}canvas.focus();}
function pause(){if(state.mode!=='playing')return;state.mode='menu';releaseInput();exitPointer();refreshMenu();$('menu').classList.remove('hidden');document.body.classList.add('in-menu');}
function setMap(open){if(!state.ready||state.mode==='result')return;c2.open=open;releaseInput();if(open){state.mode='c2';exitPointer();$('menu').classList.add('hidden');document.body.classList.remove('in-menu');$('c2').classList.remove('hidden');document.body.classList.add('in-c2');c2.updateInfo();$('close-map').focus();}else{$('c2').classList.add('hidden');document.body.classList.remove('in-c2');play();}}
$('play').onclick=play;$('open-map').onclick=()=>setMap(true);$('close-map').onclick=()=>setMap(false);$('settings-toggle').onclick=()=>{$('settings').classList.toggle('hidden');};$('sensitivity').oninput=e=>sensitivity=Number(e.target.value);$('volume').oninput=e=>sound.setVolume(Number(e.target.value));$('fullscreen').onclick=()=>{const result=document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();result?.catch(()=>notify('Celou obrazovku lze zapnout klávesou F11.',4));};
function reset(){releaseInput();state.position.set(world.spawn.x,0,world.spawn.z);state.health=100;state.damageFlash=0;state.kills=0;state.lastDamage=-100;state.speed=0;lastShot=-1;poseAccumulator=0;accumulator=0;if(character)character.root.rotation.z=0;state.yaw=0;state.pitch=-.12;state.crouched=false;state.ammo=30;state.reserve=180;state.shots=state.hits=state.score=state.time=state.reload=state.recoil=0;state.stamina=1;velocity.set(0,0,0);world.targets.forEach(t=>{t.down=t.everHit=false;t.angle=t.velocity=0;t.restore=0;});bullets.length=particles.length=casings.length=events.length=0;for(const t of tracers){scene.remove(t.line);t.line.geometry.dispose();t.line.material.dispose();}tracers.length=0;for(const d of decals){d.mesh.removeFromParent();d.mesh.geometry.dispose();}decals.length=0;c2.waypoint=null;c2.selected=null;$('event-log').innerHTML='<p class="subtle">Čeká se na první zásah.</p>';camera.position.copy(state.position).add(new THREE.Vector3(.8,2,3));if(state.level==='baghdad'){mission.reset($('difficulty').value);notify('TICHÝ PROUD · Obnovte napájení kliniky v západním dvoře.',5);}else notify('Nový výcvik. Všech 10 cílů připraveno.');$('result').classList.add('hidden');document.body.classList.remove('in-result');updateLevelUI();}
$('reset-training').onclick=()=>{reset();state.mode='menu';play();};
function refreshMenu(){
  const city=state.level==='baghdad';
  $('menu-title').innerHTML='VANGUARD<span>'+(city?'OPERATION / SILENT CURRENT':'FIELD TRAINING')+'</span>';
  $('menu-description').textContent=city?'Bagdád. Klinika ztratila napájení a spojení. Obnovte proud, zajistěte seznam pacientů a přivolejte evakuaci.':'Vstupte do polygonu. Ověřte si pohyb, práci se zbraní a přehled o bojišti.';
  $('briefing-location').textContent=city?'Irák · Bagdád · izolovaný městský blok':'Lesní polygon · Sektor 04';
  $('briefing-task').textContent=city?'Napájení → seznam → přenos → návrat':'Zasáhnout všech 10 cvičných cílů';
  $('play-label').textContent=hasPlayed?(city?'POKRAČOVAT V MISI':'POKRAČOVAT VE VÝCVIKU'):(city?'SPUSTIT MISI / TICHÝ PROUD':'VSTOUPIT DO VÝCVIKU');
  $('difficulty-row').classList.toggle('hidden',!city);$('reset-training').textContent=city?'RESTARTOVAT MISI':'NOVÝ VÝCVIK';
  $('location-number').textContent=city?'02':'01';$('location-name').textContent=city?'BAGDÁD / TICHÝ PROUD':'VÝCVIKOVÝ POLYGON';$('location-coordinate').textContent=city?'IRÁK · FIKTIVNÍ MĚSTSKÝ BLOK':'49° 41′ N · 17° 31′ E · SIMULACE';
  document.querySelectorAll('[data-level]').forEach(b=>{b.classList.toggle('selected',b.dataset.level===state.level);b.setAttribute('aria-pressed',String(b.dataset.level===state.level));});
  const d=DIFFICULTIES[$('difficulty').value];$('difficulty-description').textContent=d.name+' · '+d.enemies+' stráží · 30 + '+d.reserve+' nábojů · lékárnička +'+d.medkit;
}
function updateLevelUI(){
  const city=state.level==='baghdad';document.body.classList.toggle('in-baghdad',city);
  $('mission-module').textContent=city?'OPERACE / MISE 02':'VÝCVIKOVÝ MODUL 01';$('mission-title').innerHTML=city?'TICHÝ <span>PROUD</span>':'POLYGON <span>04</span>';
  $('mission-subtitle').textContent=city?'BAGDÁD / EVAKUACE KLINIKY':'VOLNÝ STŘELECKÝ VÝCVIK';$('completion-label').textContent=city?'ÚKOLY':'CÍLE';$('area-label').textContent=city?'BAGDÁD / '+DIFFICULTIES[state.difficulty].name.toUpperCase():'CVIČNÁ OBLAST';
  $('health-panel').classList.toggle('hidden',!city);$('objective-panel').classList.toggle('hidden',!city);$('objective-marker').classList.toggle('hidden',!city);refreshMenu();
}
function selectLevel(id){if(!state.ready||id===state.level)return;releaseInput();exitPointer();world.scene.removeFromParent();world=id==='baghdad'?cityWorld:trainingWorld;scene.add(world.scene);scene.background=world.scene.background;scene.fog=world.scene.fog;state.level=id;state.mode='menu';hasPlayed=false;c2.setWorld(world);reset();quality($('quality').value);camera.position.set(world.spawn.x+.6,2,world.spawn.z+3);character.root.position.copy(state.position);character.update(.016,{speed:0,sprint:false,crouched:false,aiming:false,yaw:0,pitch:-.12,reload:0,recoil:0,time:0,moveX:0,moveZ:0});updateCamera(1);}
document.querySelectorAll('[data-level]').forEach(button=>button.onclick=()=>selectLevel(button.dataset.level));
$('difficulty').onchange=()=>{if(state.level==='baghdad'){reset();hasPlayed=false;refreshMenu();}};
function finishMission(success){state.mode='result';releaseInput();exitPointer();$('result').classList.remove('hidden');document.body.classList.add('in-result');$('result-kicker').textContent=success?'EVAKUACE POTVRZENA':'SPOJENÍ ZTRACENO';$('result-title').textContent=success?'MISE SPLNĚNA':'OPERÁTOR VYŘAZEN';$('result-description').textContent=success?'Klinika má proud. Evakuační seznam a souřadnice dorazily k týmu. Vrátili jste se k transportu.':'Mise není dokončena. Používejte kryty, obcházejte hlídky a vyhledejte zdravotnické brašny.';$('result-stats').textContent=formatTime(state.time)+' · '+DIFFICULTIES[state.difficulty].name+' · '+state.kills+' vyřazených stráží · '+state.score+' bodů';if(!success)character.root.rotation.z=1.35;}
$('retry-mission').onclick=()=>{reset();state.mode='menu';play();};
$('result-menu').onclick=()=>{reset();hasPlayed=false;state.mode='menu';$('menu').classList.remove('hidden');document.body.classList.add('in-menu');refreshMenu();};

function resize(){const ratio=renderer.getPixelRatio();renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();composer.setSize(innerWidth,innerHeight);fxaa.material.uniforms.resolution.value.set(1/(innerWidth*ratio),1/(innerHeight*ratio));}
function quality(value){const ultra=value==='ultra',medium=value==='medium';renderer.setPixelRatio(Math.min(devicePixelRatio,ultra?2:medium?1:1.5));world.sun.shadow.mapSize.set(ultra?4096:medium?1024:2048,ultra?4096:medium?1024:2048);if(world.sun.shadow.map){world.sun.shadow.map.dispose();world.sun.shadow.map=null;}world.grass.visible=!medium;grade.enabled=!medium;resize();}
$('quality').onchange=e=>quality(e.target.value);addEventListener('resize',resize);resize();
document.addEventListener('contextmenu',e=>e.preventDefault());
document.addEventListener('keydown',e=>{if(['Tab','Space','KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Tab'&&!e.repeat){if(state.mode==='playing'||state.mode==='c2')setMap(!c2.open);return;}if(e.code==='Escape'){if(state.mode==='c2')setMap(false);else pause();return;}if(state.mode!=='playing')return;keys.add(e.code);if(!e.repeat){if(e.code==='KeyC')state.crouched=!state.crouched;if(e.code==='KeyR')startReload();if(e.code==='KeyE'&&state.level==='baghdad')mission.interact();if(e.code==='KeyE'&&state.level==='training'&&state.position.distanceTo(world.supply)<3){state.reserve=180;sound.reload(1);notify('Munice doplněna · 180 nábojů v rezervě');}if(e.code==='KeyX'&&state.level==='training'){world.targets.forEach(t=>{t.down=false;t.restore=0;});notify('Terče znovu aktivovány');}}});
document.addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('mousedown',e=>{if(state.mode!=='playing')return;if(e.button===0){fireHeld=true;sound.start();}if(e.button===2){aimHeld=true;dragLook=true;lastMouse={x:e.clientX,y:e.clientY};} });
document.addEventListener('mouseup',e=>{if(e.button===0)fireHeld=false;if(e.button===2){aimHeld=false;dragLook=false;}});
document.addEventListener('mousemove',e=>{if(state.mode!=='playing')return;let dx=e.movementX,dy=e.movementY;if(document.pointerLockElement!==canvas){if(!dragLook)return;dx=e.clientX-lastMouse.x;dy=e.clientY-lastMouse.y;lastMouse={x:e.clientX,y:e.clientY};}const sens=.0020*sensitivity*(state.aiming?.7:1);state.yaw-=dx*sens;state.pitch=clamp(state.pitch-dy*sens,-.7,.85);});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas&&state.mode==='playing')pause();});
addEventListener('blur',()=>{if(state.mode==='playing')pause();else releaseInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')pause();});
function startReload(){if(state.reload>0||state.ammo===30)return;if(!state.reserve){notify(state.level==='baghdad'?'Rezerva prázdná. Vyhledejte muniční bednu označenou na mapě.':'Rezerva prázdná. Doplňte munici u kontejneru LOGISTIKA.');return;}state.reload=.0001;reloadStage=0;sound.reload();}
function emitImpact(point,normal,target){const n=normal||new THREE.Vector3(0,1,0);for(let i=0;i<(target?11:7);i++){if(particles.length>=180)particles.shift();particles.push({p:point.clone(),v:n.clone().multiplyScalar(1+Math.random()*2).add(new THREE.Vector3((Math.random()-.5)*2,Math.random()*2,(Math.random()-.5)*2)),life:.25+Math.random()*.4,max:.65,size:.012+Math.random()*.025});}}
function impact(hit,bullet){if(hit.object.userData.enemy){const enemy=hit.object.userData.enemy;if(mission.hit(enemy,hit.object.userData.head)){state.hits++;hitTimer=.2;hitTextTimer=1;$('hit-info').textContent=enemy.alive?'ZÁSAH':'HROZBA VYŘAZENA +100';$('hit-info').classList.remove('hidden');sound.hit();emitImpact(hit.point,null,true);}return;}let normal=hit.face?.normal.clone()||new THREE.Vector3(0,1,0);normal.transformDirection(hit.object.matrixWorld);emitImpact(hit.point,normal,hit.object.userData.target);const target=hit.object.userData.target;if(target&&!target.down){target.down=true;target.everHit=true;target.restore=5.5;target.velocity=2.2;state.hits++;const local=target.board.worldToLocal(hit.point.clone()),head=local.y>.48;const score=head?150:100;state.score+=score;hitTimer=.2;hitTextTimer=1.2;$('hit-info').textContent=`${head?'PŘESNÝ ZÁSAH':'ZÁSAH'} +${score}`;$('hit-info').classList.remove('hidden');sound.hit();events.unshift({id:target.id,range:Math.round(hit.point.distanceTo(bullet.origin)),time:state.time,score});if(events.length>6)events.pop();$('event-log').innerHTML=events.map(e=>`<div>T–${String(e.id).padStart(2,'0')} <b>+${e.score}</b><span>${formatTime(e.time)} · ${e.range} METRŮ</span></div>`).join('');if(world.targets.every(t=>t.everHit))notify('VÝCVIK SPLNĚN · Zasaženo všech 10 cílů. Pokračujte nebo zahajte nový výcvik.',5);}
  const mesh=new THREE.Mesh(new THREE.CircleGeometry(target?.024:.037,8),new THREE.MeshBasicMaterial({color:target?'#211f1a':'#303127',transparent:true,opacity:.85,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-4}));mesh.position.copy(hit.point).addScaledVector(normal,.006);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);scene.add(mesh);if(target){target.pivot.attach(mesh);}decals.push({mesh,life:24});if(decals.length>70){const d=decals.shift();d.mesh.removeFromParent();d.mesh.geometry.dispose();d.mesh.material.dispose();}}
function shoot(){if(state.mode!=='playing'||state.health<=0)return;if(state.reload>0||state.sprint||state.time-lastShot<.098)return;lastShot=state.time;if(state.ammo<=0){sound.empty();startReload();return;}state.ammo--;state.shots++;state.recoil=Math.min(1.6,state.recoil+.95);sound.shot();if(state.level==='baghdad')mission.hearShot(state.position);
  // Camera ray picks the visible point, muzzle ray determines the real trajectory.
  cameraRay.setFromCamera(new THREE.Vector2(0,0),camera);cameraRay.far=300;const visible=cameraRay.intersectObjects(world.shootMeshes,false)[0];aimPoint.copy(visible?visible.point:cameraRay.ray.at(300,new THREE.Vector3()));
  const origin=character.muzzle.getWorldPosition(new THREE.Vector3()),direction=aimPoint.clone().sub(origin).normalize();const spread=(state.aiming?.00065:.0075)*(state.crouched?.55:1)*(1+state.speed*.28);direction.add(new THREE.Vector3((Math.random()-.5)*spread,(Math.random()-.5)*spread,(Math.random()-.5)*spread)).normalize();
  const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([origin,origin]),new THREE.LineBasicMaterial({color:'#f9d48d',transparent:true,opacity:.8,depthWrite:false}));line.frustumCulled=false;scene.add(line);const tracer={line,life:.09};tracers.push(tracer);const bullet={p:origin.clone(),origin:origin.clone(),v:direction.multiplyScalar(MUZZLE_SPEED),age:0,tracer};
  // Prevent a muzzle which protrudes through a thin wall from bypassing cover.
  const shoulder=state.position.clone().add(new THREE.Vector3(0,1.38-character.crouch*.48,0)),toMuzzle=origin.clone().sub(shoulder);raycaster.set(shoulder,toMuzzle.clone().normalize());raycaster.far=toMuzzle.length();const blocked=raycaster.intersectObjects(world.shootMeshes,false)[0];if(blocked)impact(blocked,bullet);else bullets.push(bullet);
  const right=new THREE.Vector3(Math.cos(state.yaw),0,-Math.sin(state.yaw));if(casings.length>=55)casings.shift();casings.push({p:origin.clone().addScaledVector(currentForward(),-.6),v:right.multiplyScalar(1.3+Math.random()).add(new THREE.Vector3(0,1.4+Math.random(),0)),life:7,rotation:Math.random()*6});
  state.pitch=clamp(state.pitch+(state.aiming?.0035:.0022),-.7,.85);
}
function updateBullets(dt){for(let i=bullets.length-1;i>=0;i--){const b=bullets[i],step=integrateBullet(b.p,b.v,dt),next=new THREE.Vector3(step.position.x,step.position.y,step.position.z),segment=next.clone().sub(b.p),distance=segment.length();raycaster.set(b.p,segment.normalize());raycaster.far=distance;const hit=raycaster.intersectObjects(world.shootMeshes,false)[0];const end=hit?hit.point:next;b.tracer.line.geometry.attributes.position.setXYZ(0,b.p.x,b.p.y,b.p.z);b.tracer.line.geometry.attributes.position.setXYZ(1,end.x,end.y,end.z);b.tracer.line.geometry.attributes.position.needsUpdate=true;b.tracer.life=.09;b.p.copy(end);b.v.set(step.velocity.x,step.velocity.y,step.velocity.z);b.age+=dt;if(hit){impact(hit,b);bullets.splice(i,1);}else if(b.age>.4||b.p.y<-5)bullets.splice(i,1);}}
function fixedUpdate(dt){if(state.mode!=='playing')return;state.time+=dt;state.aiming=aimHeld&&state.reload===0;const mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),mz=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0);state.sprint=(keys.has('ShiftLeft')||keys.has('ShiftRight'))&&mz>0&&!state.crouched&&!state.aiming&&state.reload===0&&state.stamina>.03;state.stamina=clamp(state.stamina+(state.sprint?-.16:.12)*dt,0,1);const speed=state.crouched?1.15:state.sprint?5.1:state.aiming?1.65:2.45;
  const input=new THREE.Vector3(mx,0,-mz);if(input.lengthSq()>0)input.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),state.yaw).multiplyScalar(speed);velocity.x=damp(velocity.x,input.x,13,dt);velocity.z=damp(velocity.z,input.z,13,dt);
  const before=state.position.clone(),candidate={x:clamp(state.position.x+velocity.x*dt,world.bounds.minX,world.bounds.maxX),z:clamp(state.position.z+velocity.z*dt,world.bounds.minZ,world.bounds.maxZ)};const resolved=resolveCircle(candidate,.31,world.obstacles);state.position.x=resolved.x;state.position.z=resolved.z;state.speed=state.position.distanceTo(before)/dt;state.recoil=damp(state.recoil,0,15,dt);
  if(state.reload>0){state.reload+=dt/1.645;if(state.reload>.42&&reloadStage===0){sound.reload();reloadStage=1;}if(state.reload>.78&&reloadStage===1){sound.reload(1);reloadStage=2;}if(state.reload>=1){Object.assign(state,reloadAmmo(state.ammo,state.reserve));state.reload=0;}}
  world.update(dt,state.time);character.root.position.copy(state.position);poseAccumulator+=dt;if(poseAccumulator>=1/60){character.update(poseAccumulator,{speed:state.speed,sprint:state.sprint,crouched:state.crouched,aiming:state.aiming,yaw:state.yaw,pitch:state.pitch,reload:state.reload,recoil:state.recoil,time:state.time,moveX:mx,moveZ:mz});poseAccumulator=0;}
  if(fireHeld)shoot();updateBullets(dt);if(state.level==='baghdad')mission.update(dt,keys.has('KeyE')); stepTimer-=state.speed*dt;if(stepTimer<=0&&state.speed>.4){sound.step(state.crouched);stepTimer=state.sprint?1.65:state.crouched?.66:1.1;}
}
function updateCamera(dt){const aim=character?character.aim:0,crouch=character?character.crouch:0;currentForward();const forward=lookDirection.clone(),right=new THREE.Vector3(Math.cos(state.yaw),0,-Math.sin(state.yaw));cameraTarget.copy(state.position).add(new THREE.Vector3(0,1.45-crouch*.47,0));cameraTarget.addScaledVector(right,.52+aim*.08);const distance=THREE.MathUtils.lerp(3.7,1.45,aim);cameraDesired.copy(cameraTarget).addScaledVector(forward,-distance);cameraDesired.y+=.22*(1-aim);const from=state.position.clone().add(new THREE.Vector3(0,1.35-crouch*.44,0)),segment=cameraDesired.clone().sub(from);raycaster.set(from,segment.clone().normalize());raycaster.far=segment.length()+.18;const blocked=raycaster.intersectObjects(world.shootMeshes,false).find(h=>!h.object.userData.target&&!h.object.userData.enemy);if(blocked)cameraDesired.copy(from).addScaledVector(segment.normalize(),Math.max(.25,blocked.distance-.18));camera.position.lerp(cameraDesired,1-Math.exp(-15*dt));if(character){const clearance=camera.position.distanceTo(from);character.model.visible=clearance>1.05;character.weapon.visible=clearance>.6;}const target=camera.position.clone().addScaledVector(forward,30);camera.lookAt(target);camera.fov=damp(camera.fov,aim>0?58-aim*17:58,12,dt);camera.updateProjectionMatrix();camera.updateMatrixWorld(true);}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue;}p.v.y-=4*dt;p.p.addScaledVector(p.v,dt);dummy.position.copy(p.p);dummy.rotation.set(0,0,0);dummy.scale.setScalar(p.size*p.life/p.max);dummy.updateMatrix();sparks.setMatrixAt(i,dummy.matrix);}sparks.count=particles.length;sparks.instanceMatrix.needsUpdate=true;
  for(let i=casings.length-1;i>=0;i--){const c=casings[i];c.life-=dt;if(c.life<=0){casings.splice(i,1);continue;}c.v.y-=9.81*dt;c.p.addScaledVector(c.v,dt);if(c.p.y<.028){c.p.y=.028;c.v.y=Math.abs(c.v.y)*.3;c.v.x*=.7;c.v.z*=.7;}c.rotation+=dt*c.v.length()*4;dummy.position.copy(c.p);dummy.rotation.set(c.rotation,c.rotation*.5,c.rotation*.3);dummy.scale.setScalar(1);dummy.updateMatrix();casingsMesh.setMatrixAt(i,dummy.matrix);}casingsMesh.count=casings.length;casingsMesh.instanceMatrix.needsUpdate=true;
  for(let i=tracers.length-1;i>=0;i--){const t=tracers[i];t.life-=dt;t.line.material.opacity=Math.max(0,t.life/.09)*.7;if(t.life<=0&&!bullets.some(b=>b.tracer===t)){scene.remove(t.line);t.line.geometry.dispose();t.line.material.dispose();tracers.splice(i,1);}}
  for(let i=decals.length-1;i>=0;i--){decals[i].life-=dt;if(decals[i].life<0){decals[i].mesh.removeFromParent();decals[i].mesh.geometry.dispose();decals[i].mesh.material.dispose();decals.splice(i,1);}}
}
function formatTime(t){return`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t)%60).padStart(2,'0')}`;}
const compassTicks=[];for(let i=0;i<25;i++){const el=document.createElement('span');$('compass-tape').appendChild(el);compassTicks.push(el);}
function updateHUD(dt){const heading=((-state.yaw*180/Math.PI)%360+360)%360,base=Math.floor(heading/15)*15;$('bearing').textContent=`${String(Math.round(heading)%360).padStart(3,'0')}°`;const w=$('compass').clientWidth;for(let i=0;i<25;i++){const angle=base+(i-12)*15,normalized=(angle%360+360)%360;const label={0:'N',45:'NE',90:'E',135:'SE',180:'S',225:'SW',270:'W',315:'NW'}[normalized]||String(normalized).padStart(3,'0');compassTicks[i].style.left=`${w/2+(angle-heading)*3}px`;compassTicks[i].textContent=label;compassTicks[i].style.color=normalized%90===0?'#f4d09c':'#e4e8d8';}
  $('ammo').textContent=String(state.ammo).padStart(2,'0');$('reserve').textContent=state.reserve;$('hits').textContent=String(state.hits).padStart(2,'0');$('accuracy').textContent=state.shots?`${Math.round(state.hits/state.shots*100)}%`:'—';$('targets-count').textContent=state.level==='baghdad'?Math.min(4,mission.stage+(mission.completed?1:0))+'/4':world.targets.filter(t=>t.everHit).length+'/10';$('elapsed').textContent=formatTime(state.time);$('stamina').style.width=`${state.stamina*100}%`;document.body.classList.toggle('low-ammo',state.ammo<=5);$('stance').textContent=state.reload?'PŘEBÍJENÍ':state.crouched?(state.speed>.3?'POHYB V KLEKU':'KLEK'):state.sprint?'BĚH':state.aiming?'MÍŘENÍ':state.speed>.3?'CHŮZE':'PŘIPRAVEN';$('weapon-state').textContent=state.reload?'PŘEBÍJENÍ…':state.ammo===0?'PRÁZDNÝ ZÁSOBNÍK':state.sprint?'ZBRAŇ SKLOPENA':'ZBRAŇ PŘIPRAVENA';$('reload-progress').style.width=`${state.reload*100}%`;$('crosshair').classList.toggle('visible',state.aiming&&state.mode==='playing');$('crosshair').style.setProperty('--gap',`${5+state.recoil*7+state.speed*1.4}px`);$('hitmarker').style.opacity=Math.min(1,hitTimer*7);if(state.level==='baghdad')updateMissionHUD();else{$('interaction').classList.toggle('hidden',state.position.distanceTo(world.supply)>3||state.mode!=='playing');$('interaction-text').textContent='DOPLNIT MUNICI';$('interaction-progress').style.width='0%';$('damage-overlay').style.opacity='0';}
  if(state.aiming){cameraRay.setFromCamera(new THREE.Vector2(),camera);cameraRay.far=300;const h=cameraRay.intersectObjects(world.shootMeshes,false)[0];$('range').textContent=h?`${Math.round(h.distance)} M`:'> 300 M';$('target-label').textContent=h?.object.userData.target?`T–${String(h.object.userData.target.id).padStart(2,'0')} / ${Math.round(h.distance)} M`:'';}else{$('range').textContent='DOSAH 300 M';$('target-label').textContent='';}
  if(notificationTimer>0){notificationTimer-=dt;if(notificationTimer<=0)$('notification').style.opacity='0';}if(hitTimer>0)hitTimer-=dt;if(hitTextTimer>0){hitTextTimer-=dt;if(hitTextTimer<=0)$('hit-info').classList.add('hidden');}c2.render(dt);
}

function updateMissionHUD(){
  const obj=mission.objective,interaction=mission.interaction(),distance=Math.hypot(obj.x-state.position.x,obj.z-state.position.z);
  $('health-value').textContent=Math.ceil(state.health);$('health-fill').style.width=state.health+'%';$('health-panel').classList.toggle('critical',state.health<=30);$('damage-overlay').style.opacity=Math.max(state.damageFlash*.75,state.health<=25?.18:0);$('damage-direction').style.transform='rotate('+(-state.damageYaw-state.yaw+Math.PI)+'rad)';
  $('objective-number').textContent=String(mission.stage+1).padStart(2,'0')+' / 04';$('objective-title').textContent=obj.title;
  $('objective-detail').textContent=mission.transmitting?(distance>12?'Přenos pozastaven. Vraťte se do 12 m od rádia.':'Udržujte spojení · '+Math.ceil(25-mission.upload)+' s'):obj.detail;
  $('objective-distance').textContent=Math.round(distance)+' M';$('transmit-progress').style.width=(mission.upload/25*100)+'%';$('transmit-track').classList.toggle('hidden',!mission.transmitting);
  $('interaction').classList.toggle('hidden',!interaction||state.mode!=='playing');$('interaction-text').textContent=interaction?(interaction.type==='objective'?'DRŽET E · ':'')+interaction.text:'';$('interaction-progress').style.width=(mission.progress*100)+'%';
  const point=new THREE.Vector3(obj.x,2.5,obj.z).project(camera);const visible=point.z<1&&Math.abs(point.x)<.9&&Math.abs(point.y)<.8&&distance>3&&state.mode==='playing';$('objective-marker').classList.toggle('hidden',!visible);if(visible){$('objective-marker').style.left=((point.x*.5+.5)*innerWidth)+'px';$('objective-marker').style.top=((-point.y*.5+.5)*innerHeight)+'px';$('objective-marker').textContent=String(mission.stage+1).padStart(2,'0')+' / '+Math.round(distance)+' m';}
}

async function boot(){try{character=await makeCharacter(scene);const cityScene=new THREE.Scene();cityWorld=await makeBaghdad(cityScene);mission=new BaghdadMission(cityWorld,state,{notify,finish:finishMission,hurt:()=>sound.hurt(),pickup:()=>sound.reload(1),enemyShot:gain=>sound.enemyShot(gain),objective:()=>sound.hit()});await mission.init();state.reserve=180;state.level='training';character.root.position.copy(state.position);character.update(.016,{speed:0,sprint:false,crouched:false,aiming:false,yaw:0,pitch:state.pitch,reload:0,recoil:0,time:0,moveX:0,moveZ:0});camera.position.copy(state.position).add(new THREE.Vector3(.65,1.9,3.2));updateCamera(1);state.ready=true;$('play').disabled=false;document.querySelectorAll('[data-level]').forEach(b=>b.disabled=false);updateLevelUI();}catch(error){console.error(error);$('play-label').textContent='NAČTENÍ SELHALO';$('load-error').classList.remove('hidden');$('load-error').textContent='Model se nepodařilo načíst. Zkontrolujte, že index.html, style.css a game.bundle.js zůstaly ve stejné složce.';}}
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-lastTime)/1000,.05);lastTime=now;frameTime+=dt;fpsFrames++;fpsTime+=dt;if(fpsTime>.6){$('fps').textContent=Math.round(fpsFrames/fpsTime);fpsTime=0;fpsFrames=0;}
  if(state.ready){if(state.mode==='playing'){accumulator+=dt;let steps=0;while(accumulator>=FIXED_STEP&&steps<6){fixedUpdate(FIXED_STEP);accumulator-=FIXED_STEP;steps++;}updateParticles(dt);updateCamera(dt);}else{accumulator=0;if(state.mode==='menu'&&!hasPlayed){character.update(dt,{speed:0,sprint:false,crouched:false,aiming:false,yaw:0,pitch:state.pitch,reload:0,recoil:0,time:frameTime,moveX:0,moveZ:0});updateCamera(dt);}}
    uiTime+=dt;if(uiTime>.06){updateHUD(uiTime);uiTime=0;}}
  grade.uniforms.time.value=frameTime;renderer.info.reset();composer.render();
}
boot();requestAnimationFrame(frame);
// Explicit opt-in diagnostic surface for integration tests; absent in normal play.
if(new URLSearchParams(location.search).has('test'))window.__VANGUARD__={state,get world(){return world;},get mission(){return mission;},selectLevel,get character(){return character;},camera,renderer,c2,play,pause,reset,shoot,startReload,setMap,updateCamera,fixedUpdate,get bullets(){return bullets;},get diagnostics(){return{ready:state.ready,bones:character?.boneCount,clips:character?.clips,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles};}};

