import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1600,height:1000},offline:true});
const page=await context.newPage(),errors=[],requests=[],results=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
async function check(name,fn){await fn();results.push(name);console.log('PASS',name);}
const read=()=>page.evaluate(()=>({ready:__VANGUARD__.state.ready,mode:__VANGUARD__.state.mode,position:__VANGUARD__.state.position.toArray(),ammo:__VANGUARD__.state.ammo,reserve:__VANGUARD__.state.reserve,hits:__VANGUARD__.state.hits,shots:__VANGUARD__.state.shots,crouched:__VANGUARD__.state.crouched,aiming:__VANGUARD__.state.aiming,reload:__VANGUARD__.state.reload,time:__VANGUARD__.state.time,fov:__VANGUARD__.camera.fov}));
try{
  await page.goto(pathToFileURL(path.resolve(process.env.GAME_FILE||'index.html')).href+'?test');
  await page.waitForFunction(()=>window.__VANGUARD__?.state.ready,null,{timeout:30000});
  await page.waitForTimeout(900);
  await check('file:// runs with browser completely offline and a real skinned skeleton',async()=>{assert.equal((await read()).ready,true);const d=await page.evaluate(()=>__VANGUARD__.diagnostics);assert.ok(d.bones>=40);assert.ok(d.clips.includes('Walk'));assert.equal(requests.length,0);});
  await page.screenshot({path:'tmp/menu.png'});await page.click('#play');await page.waitForTimeout(400);
  await check('W moves forward; A strafes left',async()=>{const a=await read();await page.keyboard.down('KeyW');await page.waitForTimeout(650);await page.keyboard.up('KeyW');const b=await read();assert.ok(a.position[2]-b.position[2]>1);await page.keyboard.down('KeyA');await page.waitForTimeout(450);await page.keyboard.up('KeyA');const c=await read();assert.ok(c.position[0]<b.position[0]-.65);});
  await check('crouching lowers the skeleton, and crouch walking is slower',async()=>{await page.waitForTimeout(250);const standing=await page.evaluate(()=>__VANGUARD__.character.bones.Hips.matrixWorld.elements[13]);await page.keyboard.press('KeyC');await page.waitForTimeout(400);const crouched=await page.evaluate(()=>__VANGUARD__.character.bones.Hips.matrixWorld.elements[13]);assert.ok(standing-crouched>.35);assert.equal((await read()).crouched,true);const a=await read();await page.keyboard.down('KeyW');await page.waitForTimeout(600);await page.keyboard.up('KeyW');const b=await read();assert.ok(a.position[2]-b.position[2]>.4&&a.position[2]-b.position[2]<.95);await page.screenshot({path:'tmp/crouch.png'});await page.keyboard.press('KeyC');});
  await check('RMB blends into right-shoulder aim and shows crosshair',async()=>{await page.mouse.down({button:'right'});await page.waitForTimeout(450);const s=await read();assert.equal(s.aiming,true);assert.ok(s.fov<43);assert.ok(await page.locator('#crosshair').evaluate(el=>el.classList.contains('visible')));const d=await page.evaluate(()=>__VANGUARD__.camera.position.x-__VANGUARD__.state.position.x);assert.ok(d>.45);await page.screenshot({path:'tmp/aim.png'});});
  await check('a bullet cast from the muzzle hits the aimed target and knocks it down',async()=>{
    await page.evaluate(()=>{const g=__VANGUARD__;g.state.position.set(0,0,18);g.state.yaw=0;g.state.pitch=0;for(let i=0;i<7;i++){g.updateCamera(1);const t=g.world.targets[1];const dx=t.x-g.camera.position.x,dy=1.55-g.camera.position.y,dz=t.z-g.camera.position.z;g.state.yaw=Math.atan2(-dx,-dz);g.state.pitch=Math.atan2(dy,Math.hypot(dx,dz));}});
    await page.waitForTimeout(250);await page.mouse.down();await page.waitForTimeout(25);await page.mouse.up();await page.waitForTimeout(200);const s=await read();assert.equal(s.ammo,29);assert.equal(s.shots,1);assert.equal(s.hits,1);assert.equal(await page.evaluate(()=>__VANGUARD__.world.targets[1].down),true);await page.screenshot({path:'tmp/hit.png'});
  });
  await page.mouse.up({button:'right'});
  await check('reloading blocks firing and transfers exactly the missing rounds',async()=>{await page.keyboard.press('KeyR');await page.waitForTimeout(350);assert.ok((await read()).reload>0);await page.mouse.down();await page.waitForTimeout(180);await page.mouse.up();assert.equal((await read()).ammo,29);await page.screenshot({path:'tmp/reload.png'});await page.waitForFunction(()=>__VANGUARD__.state.reload===0,null,{timeout:5000});const s=await read();assert.equal(s.ammo,30);assert.equal(s.reserve,179);});
  await check('C2 pauses simulation, supports waypoints and zoom, and Tab returns to play',async()=>{await page.keyboard.press('Tab');await page.waitForTimeout(200);const a=await read();assert.equal(a.mode,'c2');await page.waitForTimeout(220);assert.equal((await read()).time,a.time);const rect=await page.locator('#tactical-map').boundingBox();await page.mouse.click(rect.x+rect.width*.53,rect.y+rect.height*.4);assert.ok(await page.evaluate(()=>__VANGUARD__.c2.waypoint));await page.locator('#zoom-in').click();assert.ok(await page.evaluate(()=>__VANGUARD__.c2.zoom>1));await page.screenshot({path:'tmp/c2.png'});await page.keyboard.press('Tab');await page.waitForTimeout(220);assert.equal((await read()).mode,'playing');});
  await check('colliders prevent walking through the container',async()=>{await page.evaluate(()=>{const g=__VANGUARD__;g.state.position.set(-20,0,11);g.state.yaw=0;g.state.pitch=-.1;});await page.keyboard.down('KeyW');await page.waitForTimeout(1400);await page.keyboard.up('KeyW');const s=await read();assert.ok(s.position[2]>=9.3);assert.ok(s.position[2]<9.6);});
  await check('supply interaction refills reserve only when nearby',async()=>{await page.evaluate(()=>{__VANGUARD__.state.reserve=0;__VANGUARD__.state.position.set(-14.8,0,12.5);});await page.keyboard.press('KeyE');await page.waitForTimeout(100);assert.equal((await read()).reserve,180);});
  await check('a thin concrete barrier blocks a protruding muzzle',async()=>{await page.evaluate(()=>{const g=__VANGUARD__;g.state.position.set(9,0,-.28);g.state.yaw=0;g.state.pitch=0;g.state.crouched=true;});await page.mouse.down({button:'right'});await page.waitForTimeout(500);const hits=(await read()).hits;await page.mouse.down();await page.waitForTimeout(25);await page.mouse.up();await page.waitForTimeout(100);assert.equal((await read()).hits,hits);assert.equal(await page.evaluate(()=>__VANGUARD__.bullets.length),0);await page.mouse.up({button:'right'});});
  await check('a nearly empty reserve reloads only available ammunition',async()=>{await page.evaluate(()=>{__VANGUARD__.state.ammo=2;__VANGUARD__.state.reserve=3;});await page.keyboard.press('KeyR');await page.waitForFunction(()=>__VANGUARD__.state.reload===0&&__VANGUARD__.state.ammo===5,null,{timeout:5000});assert.equal((await read()).reserve,0);});
  await check('Escape pauses and clears held aim/fire/movement',async()=>{await page.keyboard.press('Escape');await page.waitForTimeout(250);assert.equal((await read()).mode,'menu');assert.equal((await read()).aiming,false);});
  await check('no JavaScript, shader, texture or external network errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);});
  await page.click('#play');await page.evaluate(()=>__VANGUARD__.reset());await page.waitForTimeout(3300);await page.screenshot({path:'tmp/play.png'});
  console.log('RENDER',await page.evaluate(()=>__VANGUARD__.diagnostics));
  console.log(JSON.stringify({passed:results.length,errors,externalRequests:requests},null,2));
}catch(e){await page.screenshot({path:'tmp/test-failure.png'});console.error('STATE',await read());console.error('ERRORS',errors);throw e;}finally{await browser.close();}
