'use strict';
// Development checks only. The game itself does not load Playwright or any library.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  await page.goto('http://127.0.0.1:4173/?test');
  await page.waitForFunction(() => window.IronFront);
  const out = path.join(__dirname, '..', 'output');
  fs.mkdirSync(out, { recursive: true });
  await page.screenshot({ path: path.join(out, 'briefing.png') });
  await page.getByRole('button', { name: 'ZAHÁJIT OPERACI →' }).click();
  await page.screenshot({ path: path.join(out, 'gameplay.png') });
  let state = await page.evaluate(() => IronFront.getState());
  assert.deepEqual(state.assets, [true, true, true, true], 'Generated assets load');
  assert.equal(state.entities.filter(e => e.team === 'player').length, 11);
  const initialCredits = state.credits;
  await page.evaluate(() => IronFront.test.step(26));
  state = await page.evaluate(() => IronFront.getState());
  assert(state.gathered >= 280 && state.credits > initialCredits, 'Harvester completes a round trip');
  console.log('PASS: assets, mission start, automatic harvest');
  const paths = await page.evaluate(() => {
    const t = IronFront.test;
    return [t.pathfind(800, 1000, 1900, 430), t.pathfind(800, 1000, 1600, 1230)];
  });
  assert(paths.every(p => p.length > 10), 'Paths cross the river');
  for (const route of paths) for (const p of route) {
    const rx = 1395 + Math.sin(p.y / 270) * 105 + Math.sin(p.y / 140) * 24;
    assert(Math.abs(p.x - rx) >= 64 || Math.abs(p.y - 600) < 57 || Math.abs(p.y - 1210) < 57, 'Only bridges cross water');
  }
  console.log('PASS: navigation through legal bridge cells');
  await page.getByRole('button', { name: /Vojenské depo, 1\s000/ }).click();
  const check = await page.evaluate(() => IronFront.test.canPlace('factory', 465, 780));
  assert.equal(check.ok, true, JSON.stringify(check));
  const site = await page.evaluate(() => IronFront.worldToScreen(465, 780));
  const box = await page.locator('#game').boundingBox();
  await page.mouse.click(box.x + site.x, box.y + site.y);
  state = await page.evaluate(() => IronFront.getState());
  assert(state.queue.some(q => q.type === 'factory'), 'UI places factory');
  await page.evaluate(() => IronFront.test.step(15));
  assert(await page.evaluate(() => IronFront.getState().entities.some(e => e.type === 'factory' && e.team === 'player')), 'Factory completes');
  await page.getByRole('tab', { name: /JEDNOTKY/ }).click();
  await page.getByRole('button', { name: /Leopard 2A8, 650/ }).click();
  await page.evaluate(() => IronFront.test.step(11));
  assert.equal(await page.evaluate(() => IronFront.getState().entities.filter(e => e.type === 'tank' && e.team === 'player').length), 4);
  console.log('PASS: UI construction, prerequisites, tank production');
  await page.getByRole('button', { name: /Leopard 2A8, 650/ }).click();
  const beforeCancel = await page.evaluate(() => IronFront.getState().credits);
  await page.getByRole('button', { name: 'Zrušit výrobu: Leopard 2A8' }).click();
  assert.equal(Math.floor(await page.evaluate(() => IronFront.getState().credits)), Math.floor(beforeCancel + 650));
  await page.keyboard.press('F2');
  assert((await page.evaluate(() => IronFront.getState().selected)).length >= 7);
  await page.keyboard.press('Control+1');
  await page.mouse.click(box.x + 40, box.y + box.height - 90);
  await page.keyboard.press('1');
  assert((await page.evaluate(() => IronFront.getState().selected)).length >= 7);
  await page.keyboard.press('Escape');
  const pausedTime = await page.evaluate(() => IronFront.getState().time);
  await page.evaluate(() => IronFront.test.step(4));
  assert.equal(await page.evaluate(() => IronFront.getState().time), pausedTime);
  await page.getByRole('button', { name: 'POKRAČOVAT →' }).click();
  console.log('PASS: queue refund, selection groups, pause');
  await page.evaluate(() => IronFront.test.step(50));
  assert((await page.evaluate(() => IronFront.getState().wave)) >= 1, 'Enemy wave arrives');
  await page.evaluate(() => {
    const s = IronFront.getState();
    const tank = s.entities.find(e => e.type === 'tank' && e.team === 'player');
    IronFront.test.spawn('rifle', 'enemy', tank.x + 90, tank.y);
    IronFront.test.step(12);
  });
  assert((await page.evaluate(() => IronFront.getState().kills)) > 0, 'Combat destroys an enemy');
  console.log('PASS: enemy AI wave, targeting, damage and kills');
  await page.evaluate(() => {
    const id = IronFront.getState().entities.find(e => e.type === 'fortress').id;
    IronFront.test.damage(id, 99999);
  });
  await page.getByRole('heading', { name: 'Údolí je naše.' }).waitFor();
  await page.getByRole('button', { name: 'HRÁT ZNOVU →' }).click();
  assert.equal(await page.evaluate(() => IronFront.getState().kills), 0);
  await page.evaluate(() => {
    const id = IronFront.getState().entities.find(e => e.type === 'hq').id;
    IronFront.test.damage(id, 99999);
  });
  await page.getByRole('heading', { name: 'Základna padla.' }).waitFor();
  console.log('PASS: victory, defeat and clean restart');
  await page.getByRole('button', { name: 'HRÁT ZNOVU →' }).click();
  await page.setViewportSize({ width: 1024, height: 768 });
  await page.screenshot({ path: path.join(out, 'gameplay-1024.png') });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false);
  assert.deepEqual(errors, [], `Browser errors: ${errors.join('\n')}`);
  console.log('PASS: 1024px layout and no browser errors');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
